### ISSUE TITLE
1. Java 17 is not supported 2. Placing a block in flight mode will cause your line of sight to look in that direction.

### ISSUE THREAD

**Issue by yun334022** [223225zzzkkk/easyplaceFix#1]
1. The module encounters a loading error when starting the game in version 1.20.x using Java 17, and it seems to only be compatible with versions using Java 21.
2. Placing a block in flight will cause you to look at the block you are currently turning towards.

**Comment by 223225zzzkkk** [comment]
https://github.com/223225zzzkkk/easyplaceFix/issues

**Comment by 223225zzzkkk** [comment]
1.我编写的时候使用的是java21，所以导致mod也依赖java21(后续看看能不能降低项目版本)。你应该可以使用java21来启动1.20？
2.你是在单人模式下测试的吗？多人模式下飞行状态应该可以正确放置，单人的话可以使用V3协议。
1. I wrote it using java21, so that caused the mod to depend on java21 as well (I'll follow up and see if I can downgrade the project version). You should be able to start 1.20 using java21?
2. are you testing in single player mode? Flight states should be placed correctly in multiplayer mode, and you can use the V3 protocol for single player

**Comment by yun334022** [comment]
1.20.5开始才使用java21使用前面版本就无法正常使用模组
我在多人测试的，但这多人服禁止在空中凭空放置方块，刚才我录制一段放置的状况给你看看，就是摆着会突然转头看向别处，飞行状态会解除突然掉下来

**Comment by 223225zzzkkk** [comment]
试试新版本，https://github.com/223225zzzkkk/easyplaceFix/releases/tag/%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%8F%91%E5%B8%83
我没看出来哪里有禁止空中凭空放置，转向是由于服务器主动矫正了客户端的位置。我代码中一直都没有转动客户端视角的逻辑。然后java21可以启动1.20.1

**Comment by 223225zzzkkk** [comment]
我今天看了一下飞行会失效的原因,在https://github.com/223225zzzkkk/easyplaceFix/commit/1f647e9e6c8f04d33c7266b3a07a61e5dd66e1de
这里已经顺带修复了，如果没问题我就关闭了:)
